#pragma once

#include "inttypes.h"

#define HELP_LINES 167
#define SCREEN_HELP_LINES 30
#define SCREEN_HELP_LINE_WIDTH 60

const char* __in_flash() help_head[2]={
    "[F3/Joy B-English]","[F2/Joy A-Русский]"
};

const char* __in_flash() help_text[2][HELP_LINES]={{
"                      Приветствуем!!!                      ",
" Данный проект предназначен для эмуляции серии наладонных  ",
"      игр формата \"Game & Watch\" на базе контроллера       ",
"                    [Raspberry Pi Pico]                    ",
"                                                           ",
" Группа проекта: https://t.me/ZX_MURMULATOR                ",
"                                                           ",
"-----------------------==[Авторы]==------------------------",
" Автор видео подсистемы:             Алекс Екб(@Alex_Eburg)",
"                                    Кошкин Хвост(@tecnocat)",
" Ядра эмуляции:                    https://github.com/bzhxx",
" Компрессор игр:                   https://github.com/bzhxx",
" Файловый менеджер:                  Алекс Екб(@Alex_Eburg)",
"                                    Кошкин Хвост(@tecnocat)",
" TFT драйвер:                        Алекс Екб(@Alex_Eburg)",
"                                    Кошкин Хвост(@tecnocat)",
"                                                           ",
"***********************************************************",
"                                                           ",
"----------------==[Управление в эмуляции]==----------------",
"                                                           ",
" Курсорные клавиши - Выбор направления                     ",
" X - Аппаратная кнопка А                                   ",
" Z - Аппаратная кнопка Б                                   ",
" Q - Запуск игры А                                         ",
" W - Запуск игры Б                                         ",
"                                                           ",
"--------------==[Горячие клавиши эмулятора]==--------------",
"[F1]            - Помощь                                   ",
"[Win]/[Home]    - Файловый менеджер                        ",
"                                                           ",
"[F11]           - Включение выключение HUD                 ",
"[F12]/[PrnScreen] - Вызов быстрого меню                    ",
"[Pause]         - Остановка эмуляции                       ",
"                                                           ",
"[Ctrl+Alt+Del]  - Сброс эмулятора                          ",
"[Shift+Alt+Del] - Сброс контроллера                        ",
"[Ctrl+Alt+BSpace]- Сброс до настроек по умолчанию и        ",
"                                     перезапуск контроллера",
"[NumPad +]/[Alt+PgUp] - Прибавить громкость эмуляции       ",
"[NumPad -]/[Alt+PgDn] - Убавить громкость эмуляции         ",
"[NumPad *]/[Alt+End]  - Включить/выключить режим Mute      ",
"[NumPad /]/[Alt+Del]  - Переключение набора огибающих в STS",
"                                                           ",
"                                                           ",
"*************************[Джойстик]************************",
"[START]         - Вызов быстрого меню                      ",
"                  / Выход из файлового менеджера           ",
"[A]             - Выбор файла                              ",
"[C]             - Выход на уровень вверх                   ",
"                                                           ",
"---------------------=[Меню джойстика]=--------------------",
"[FILE BROWSER]  - Вызов менеджера файлов                   ",
"    Game A      - Запуск игры А                            ",
"    Game B      - Запуск игры Б                            ",
"     TIME       - Переход в режим отображения времени      ",
"     АLАRM      - Переход в режим настройки будильника     ",
"    [HELP]      - Вызов текста помощи                      ",
"  [SETTINGS]    - Вызов меню настроек эмуляции             ",
"  Soft reset    - Перезапуск эмуляции                      ",
"  Hard reset    - Перезагрузка системы                     ",
"                                                           ",
"----------------=[Быстрые команды джойстика]=--------------",
"[START]+[A]     - Запуск игры А                            ",
"[START]+[B]     - Запуск игры Б                            ",
"                                                           ",
"[SELECT]+[UP]   - Увеличение громкости                     ",
"[SELECT]+[DOWN] - Уменьшение громкости                     ",
"[SELECT]+[LEFT] - [TFT режим] Уменьшение яркости           ",
"[SELECT]+[RIGHT]- [TFT режим] Увеличение яркости           ",
"[SELECT]+[A]    - [TFT режим] Блокировка клавиатуры        ",
"[SELECT]+[B]    - [TFT режим] Разблокировка клавиатуры     ",
"                                                           ",
"---------------------=[Джойстик в игре]=-------------------",
"[START]         - Вызов быстрого меню                      ",
"                 / Выход из файлового менеджера            ",
"[A]             - Действие назначенное в игре              ",
"[B]             - Действие назначенное в игре              ",
"[С]             - Действие назначенное в игре              ",
"                                                           ",
"------------=[Навигация в файловом менеджере]=-------------",
"[Курсорные клавиши:]                                       ",
"[Стрелка влево]  - Начало списка                           ",
"[Стрелка вправо] - Конец списка                            ",
"[Стрелка вверх]  - Предыдущий файл                         ",
"[Стрелка вниз]   - Следующий файл                          ",
"[PageUp]         - Страница вверх                          ",
"[PageDn]         - Страница вниз                           ",
"[Enter]          - Запуск образа                           ",
"[BackSpace]    - Выход на один каталог выше текущего уровня",
"[PrnScreen]   - Переключение просмотра заставки/содержимого",
"                                                           ",
"[Ins]/[Space]  - Пометка файлов для удаления               ",
"[Shift+Delete] - Вызов диалога удаления файлов             ",
"                                                           ",
"------------------=[Наcтройки эмулятора]=------------------",
"[F12]  - Настройки эмулятора (Доступны из файл менеджера)  ",
"                                                           ",
" [Boot go to]    - Выбор типа стартового экрана            ",
"  [LOGO]         - Показать заставку после старта          ",
"  [FILE MANAGER] - Показать Файловый менеджер после старта ",
"  [EMULATION]    - Запустить эмуляцию после старта         ",
"                                                           ",
" [Head Up Display]- Включение иконок поверх экрана         ",
"  [On]           - Включить отображение занятых дисководов,",
"                   процесса загрузки и слотов сохранения   ",
"  [Off]          - Чистый экран эмуляции                   ",
"  [Time]         - HUD отключатся по времени               ",
"                                                           ",
" [Sound out mode] - Переключение вывода звука              ",
"  [PWM] - Вывод звука с помошью ШИМ модуляции              ",
"  [I2S] - Вывод звука через I2S декодер        			",
"                                                           ",
" [Sound Vol] - Громкость звука эмуляции                    ",
"                                                           ",
" [Video output] -Выбор типа подключения для вывода изображ.",
"  [   AUTO   ] - Автоопределение (VGA/HDMI)                ",
"  [   VGA    ] - Вывод на VGA разъем                       ",
"  [   HDMI   ] - Вывод на HDMI разъем                      ",
"  [  ST7789  ] - Вывод на ЖК экран с чипом ST7789          ",
"  [  ST7789V ] - Вывод на ЖК экран с чипом ST7789V         ",
"  [  ILI9341 ] - Вывод на ЖК экран с чипом ILI9341         ",
"  [ ILI9341V ] - Вывод на ЖК экран с чипом ILI9341V        ",
"  [  GC9A01  ] - Вывод на ЖК экран с чипом GC9A01          ",
"                   Для применения нужна перезагрузка.      ",
"                                                           ",
" [Video framerate] - Переключение частоты обновления       ",
"  [60Hz] - подходит для большинства LCD мониторов          ",
"  [72Hz] - подходит для большинства LCD/HDMI мониторов     ",
"  [75Hz] - подходит для LCD/HDMI/CRT мониторов             ",
"  [85Hz] - подходит для CRT мониторов                      ",
"                   Для применения нужна перезагрузка.      ",
"                                                           ",
" [LCD BrightLev] - Уровнь яркости подсветки ЖК экрана      ",
"               (работает только с режимами: ST7789,ST7789V,",
"                                   ILI9341,ILI9341V,GC9A01)",
"                                                           ",
" [LCD Rotate] - Поворот изображения ЖК экрана              ",
"  [Horizont R] - Горизонтальное, разъем дисплея справа     ",
"  [Vertical R] - Вертикальное, разъем дисплея снизу        ",
"  [Horizont L] - Горизонтальное, разъем дисплея слева      ",
"  [Vertical L] - Вертикальное, разъем дисплея сверху       ",
"               (работает только с режимами: ST7789,ST7789V,",
"                                   ILI9341,ILI9341V,GC9A01)",
"                   Для применения нужна перезагрузка.      ",
"                                                           ",
" [LCD inversion] - Инверсия изображения ЖК экрана          ",
"  [ NORMAL ] - Нормальное изображение                      ",
"  [INVERTED] - Инверсия цветов изображения                 ",
"               (работает только с режимами: ST7789,ST7789V,",
"                                   ILI9341,ILI9341V,GC9A01)",
"                   Для применения нужна перезагрузка.      ",
"                                                           ",
" [LCD Pixel format] - Формат пикселей ЖК экрана            ",
"  [ BGR ] - Blue Green Red, обратный порядок               ",
"  [ RGB ] - Red Green Blue, прямой порядок                 ",
"               (работает только с режимами: ST7789,ST7789V,",
"                                   ILI9341,ILI9341V,GC9A01)",
"                   Для применения нужна перезагрузка.      ",
"                                                           ",
" [LOAD]     - Загрузить настройки c SD                     ",
" [DEFAULT]  - Загрузить настройки по умолчанию             ",
"              и перезаписать файл настроек                 ",
" [SAVE]     - Сохранить настройки на SD                    ",
" [UPDATE FIRMWARE]-Перезагрузка в режим обновления прошивки",
" [!!!REBOOT!!!]   - Перезагрузка контроллера               ",
"                                                           ",
},{
"                         Welcome!!!                        ",
" This project is designed to emulate a series of handheld  ",
"   \"Game & Watch\" format games based on a controller       ",
"                   [Raspberry Pi Pico]                     ",
"                                                           ",
" Project Group: https://t.me/ZX_MURMULATOR                 ",
"                                                           ",
"-----------------------==[Authors]==-----------------------",
" The author of the video subsystem:   Alex Ekb(@Alex_Eburg)",
"                                      Cat's Tail(@tecnocat)",
" Emulation cores:                 https://github.com/bzhxx ",
" Game Compressor:                 https://github.com/bzhxx ",
" File Manager:                        Alex Ekb(@Alex_Eburg)",
"                                      Cat's Tail(@tecnocat)",
" TFT driver:                          Alex Ekb(@Alex_Eburg)",
"                                      Cat's Tail(@tecnocat)",
"                                                           ",
"***********************************************************",
"                                                           ",
"----------------==[Controls in emulation]==----------------",
"                                                           ",
" Cursor keys - Direction                                   ",
" X - Hardware button A                                     ",
" Z - Hardware button B                                     ",
" Q - Launch Game A                                         ",
" W - Launch Game B                                         ",
"                                                           ",
"-------------==[Emulator Keyboard Shortcuts]==-------------",
"[F1] - Help                                                ",
"[Win]/[Home] - File Manager                                ",
"                                                           ",
"[F11] - Enable disable HUD                                 ",
"[F12]/[PrnScreen] - Quick menu call                        ",
"[Pause] - Pauses emulation                                 ",
"                                                           ",
"[Ctrl+Alt+Del] - Reset the emulator                        ",
"[Ctrl+Alt+Ins] - NMI emulator                              ",
"[Shift+Alt+Del] - Reset the controller                     ",
"[Ctrl+Alt+BSpace]- Set default settings and                ",
"                                          reboot controller",
"[NumPad +]/[Alt+PgUp] - Volume Up of the emulation         ",
"[NumPad -]/[Alt+PgDn] - Volume Down of the emulation       ",
"[NumPad *]/[Alt+End] - Enable/disable Mute mode            ",
"[NumPad /]/[Alt+Del] -Switch the envelope in SoftTurboSound",
"                                                           ",
"*************************[Joystick]************************",
"[START]     - Quick menu call                              ",
"        / Exiting the file manager                         ",
"[A] - File Selection                                       ",
"[C] - Exit to top folder                                   ",
"                                                           ",
"---------------------=[Joystick Menu]=---------------------",
"[FILE BROWSER] - Calling the file manager                  ",
"    Game A     - Launch Game A                             ",
"    Game B     - Launch Game B                             ",
"     TIME      - Switching to time display mode            ",
"     ALARM     - Switching to alarm setting mode           ",
"    [HELP]     - This Help                                 ",
"  [SETTINGS]   - Emulation settings menu                   ",
"  Soft reset   - Restarting the emulation                  ",
"  Hard reset   - Restarting the system                     ",
"                                                           ",
"-------------------=[Joystick hat switch]=-----------------",
"[START]+[A]     - Launch Game A                            ",
"[START]+[B]     - Launch Game B                            ",
"                                                           ",
"[SELECT]+[UP]   - Volume Up                                ",
"[SELECT]+[DOWN] - Volume Down                              ",
"[SELECT]+[LEFT] - [TFT mode] Brightness Level Down         ",
"[SELECT]+[RIGHT]- [TFT mode] Brightness Level Up           ",
"[SELECT]+[A]    - [TFT mode] Keyboard Lock                 ",
"[SELECT]+[B]    - [TFT mode] Keyboard Unlock               ",
"                                                           ",
"---------------------=[In-game joystick]=------------------",
"[START]       - Quick menu call                            ",
"         / Exiting the file manager                        ",
"[A] - The action assigned in the game                      ",
"[B] - The action assigned in the game                      ",
"[C] - The action assigned in the game                      ",
"                                                           ",
"----------------=[File Manager Navigation]=----------------",
"[Cursor keys:]                                             ",
"[Left arrow]  - Start of the list                          ",
"[Right arrow] - End of the list                            ",
"[Up Arrow]    - Previous file                              ",
"[Down arrow]  - Next file                                  ",
"[PageUp]      - Page up                                    ",
"[PageDn]      - Page down                                  ",
"[Enter]       - Launching the image                        ",
"[BackSpace]   - Exit one directory above the current level ",
"[PrnScreen]   - Switching the splash screen/content view   ",
"                                                           ",
"[Ins]/[Space] - Marking files for deletion                 ",
"[Shift+Delete]- Opens the file deletion dialog             ",
"                                                           ",
"-------------------=[Emulator Settings]=-------------------",
"[F12] - Emulator settings (Available from the file manager)",
"                                                           ",
" [Boot go to] - Select the type of start splash screen     ",
"  [LOGO]     - Show splash screen after the start          ",
"  [FILE MANAGER] - Show the File Manager after startup     ",
"  [EMULATION] - Start emulation after startup              ",
"                                                           ",
" [Head Up Display]- Enabling icons on top of the screen    ",
"  [On]            - Enable the display of occupied drives, ",
"                    loading process and save slots         ",
"  [Off]           - Clean emulation screen                 ",
"  [Time]          - HUD disappear by time                  ",
"                                                           ",
" [Sound out mode] - Switching audio output                 ",
"  [PWM] - Audio output using PWM modulation                ",
"  [I2S] - Audio output via I2S decoder                     ",
"                                                           ",
" [Sound Vol] - Sound Volume of the emulation               ",
"                                                           ",
" [Video output] - Video output type                        ",
"  [ AUTO ] - Auto Detection (VGA/HDMI)                     ",
"  [ VGA ] - Output to the VGA connector                    ",
"  [ HDMI ] - Output to the HDMI connector                  ",
"  [ ST7789 ]  - Output to LCD screen with the ST7789 chip  ",
"  [ ST7789V ] - Output to LCD screen with the ST7789V chip ",
"  [ ILI9341 ] - Output to LCD screen with the ILI9341 chip ",
"  [ ILI9341V ]- Output to LCD screen with the ILI9341V chip",
"  [ GC9A01 ]  - Output to LCD screen with GC9A01 chip      ",
"           A reboot is required to apply mode.             ",
"                                                           ",
" [Video framerate] - Switching the vertical refresh rate   ",
"  [60Hz] - Suitable for most LCD monitors                  ",
"  [72Hz] - Suitable for most LCD/HDMI monitors             ",
"  [75Hz] - Suitable for LCD/HDMI/CRT monitors              ",
"  [85Hz] - Suitable for CRT monitors                       ",
"           A reboot is required to apply mode.             ",
"                                                           ",
" [LCD BrightLev] - The brightness level for LCD backlight  ",
"                   (works only with modes: ST7789,ST7789V, ",
"                                   ILI9341,ILI9341V,GC9A01)",
"                                                           ",
" [LCD Rotate] - Rotate the image of the LCD screen         ",
"  [Horizont R] - Horizontal, display connector on the right",
"  [Vertical R] - Vertical, display connector from below    ",
"  [Horizont L] - Horizontal, display connector on the left ",
"  [Vertical L] - Vertical, display connector from above    ",
"                    (works only with modes: ST7789,ST7789V,",
"                                   ILI9341,ILI9341V,GC9A01)",
"           A reboot is required to apply mode.             ",
"                                                           ",
" [LCD inversion] - Inversion of the LCD screen image       ",
" [ NORMAL ] - Normal image                                 ",
" [INVERTED] - Inversion of image colors                    ",
"                    (works only with modes: ST7789,ST7789V,",
"                                   ILI9341,ILI9341V,GC9A01)",
"           A reboot is required to apply mode.             ",
"                                                           ",
" [LCD Pixel format] - LCD screen pixel format              ",
" [ BGR ] - Blue Green Red, reverse order                   ",
" [ RGB ] - Red Green Blue, forward order                   ",
"                    (works only with modes: ST7789,ST7789V,",
"                                   ILI9341,ILI9341V,GC9A01)",
"           A reboot is required to apply mode.             ",
"                                                           ",
" [LOAD]     - Reload settings from SD                      ",
" [DEFAULT]  - Load default settings                        ",
"                           and overwrite the settings file ",
" [SAVE]     - Save settings to SD card                     ",
" [UPDATE FIRMWARE] - Reboot to firmware update mode        ",
" [!!!REBOOT!!!] - Restart the controller                   ",
"                                                           "
}
};

/*
"-----------------=[Команды NMI Отладчика]=-----------------",
" 1 - Система счисления 16/10;                              ",
" 2 - Дамп/символьное представление;                        ",
" 3 - внесение числа в текущ. регистр;                      ",
" 4 - внесение в текущую сетку памяти;                      ",
" CS+5 - на 64 адреса назад;                                ",
" CS+6 - на 1 адрес назад;                                  ",
" CS+7 - на 1 адрес вперед;                                 ",
" CS+8 - на 64 адреса вперед;                               ",
" CS+9 - перейти к предыд. регистру;                        ",
" CS+0 - перейти к следующ. регистру;                       ",
" SS+7 - вызов подпрогр. по адресу;                         ",
" SS+0 - выход из монитора в Basic;                         ",
" ПРОБЕЛ - выделение ячейки по номеру.                      "
*/