#pragma once

#include "inttypes.h"

#define HELP_LINES 217
#define SCREEN_HELP_LINES 30
#define SCREEN_HELP_LINE_WIDTH 60

const char* __in_flash() help_head[2]={
    "[F3/Joy B-English]","[F2/Joy A-Русский]"
};

const char* __in_flash() help_text[2][HELP_LINES]={{
"                      Приветствуем!!!                      ",
" Данный проект предназначен для \"минималистичной\" эмуляции ",
"        компьютера \"ZX-Spectrum\" на базе контроллера       ",
"                    [Raspberry Pi Pico]                    ",
"                                                           ",
" Группа проекта: https://t.me/ZX_MURMULATOR                ",
"                                                           ",
"-----------------------==[Авторы]==------------------------",
" Автор ядра и железа:                Алекс Екб(@Alex_Eburg)",
" Поддержка TR-DOS:             First Last(@First_0x26_Last)",
"                                    Кошкин Хвост(@tecnocat)",
" Файловый менеджер:                  Алекс Екб(@Alex_Eburg)",
"                                    Кошкин Хвост(@tecnocat)",
" Расширение SoftTurboSound:          Алекс Екб(@Alex_Eburg)",
"                                    Кошкин Хвост(@tecnocat)",
"                                            Sa Gin(@sa gin)",
" Расширение TurboSound:              Алекс Екб(@Alex_Eburg)",
"                                            Sa Gin(@sa gin)",
"                                    Кошкин Хвост(@tecnocat)",
" Расширение Soundrive:                      Sa Gin(@sa gin)",
"                                    Кошкин Хвост(@tecnocat)",
" TFT драйвер:                        Алекс Екб(@Alex_Eburg)",
"                                    Кошкин Хвост(@tecnocat)",
"                                                           ",
"***********************************************************",
"                                                           ",
"--------------==[Горячие клавиши эмулятора]==--------------",
"[F1]            - Помощь                                   ",
"[F2]            - Меню сохранения                          ",
"[F3]            - Меню загрузки                            ",
"[Win]/[Home]    - Файловый менеджер                        ",
"                                                           ",
"[Ctrl+F1-F10]   - Сохр. образа .z80 в папку \"SAVE\" SD карты",
"[Shift+F1-F10]  - Загр.образа .z80 из папки \"SAVE\" SD карты",
"[Menu]/[Alt+F12]- Отобр. свободные слоты сохранения \"SAVE\" ",
"[F11]           - Включение выключение HUD                 ",
"[F12]/[PrnScreen] - Вызов быстрого меню                    ",
"[Pause]         - Остановка эмуляции                       ",
"                                                           ",
"[Ctrl+Alt+Del]  - Сброс эмулятора                          ",
"[Ctrl+Alt+Ins]  - NMI эмулятора                            ",
"[Shift+Alt+Del] - Сброс контроллера                        ",
"[Ctrl+Alt+BSpace]- Сброс до настроек по умолчанию и        ",
"                                     перезапуск контроллера",
"[NumPad +]/[Alt+PgUp] - Прибавить громкость эмуляции       ",
"[NumPad -]/[Alt+PgDn] - Убавить громкость эмуляции         ",
"[NumPad *]/[Alt+End]  - Включить/выключить режим Mute      ",
"[NumPad /]/[Alt+Del]  - Переключение набора огибающих в STS",
"                                                           ",
"-----------------=[Работа с \"лентой\" .tap]=----------------",
"[F5]            - Cтарт ленты                              ",
"[F6]            - Остановка ленты, повторно в режиме       ",
"                            остановки: перемотка на начало ",
"[F7]            - Cледующий блок                           ",
"[F8]            - Предыдущий блок                          ",
"[F9]            - Выброс \"кассеты\"                       ",
"                                                           ",
"*************************[Джойстик]************************",
"[START]         - Вызов быстрого меню                      ",
"                  / Выход из файлового менеджера           ",
"[A]             - Выбор файла                              ",
"[C]             - Выход на уровень вверх                   ",
"                                                           ",
"---------------------=[Меню джойстика]=--------------------",
"[FILE BROWSER]  - Вызов менеджера файлов                   ",
"  [KEYBOARD]    - Вызов экранной клавиатуры                ",
"    [SAVE]      - Вызов списка слотов для сохранения игр   ",
"    [LOAD]      - Вызов списка слотов для загрузки игр     ",
"    [TAPE]      - Вызов меню управления виртуальной лентой ",
"    [POKE]      - Вызов меню ввода чит кодов               ",
"    [HELP]      - Вызов текста помощи                      ",
" 8bit Kempston[]- Включает режим передачи всех кнопок      ",
"                  джойстика в эмуляцию.                    ",
"                  Выход из режима START+SELECT             ",
"  [SETTINGS]    - Вызов меню настроек эмуляции             ",
"  Soft reset    - Перезапуск эмуляции                      ",
"  Hard reset    - Перезагрузка системы                     ",
"                                                           ",
"----------------=[Быстрые команды джойстика]=--------------",
"[START]+[UP]    - Следующий маппинг джойстика              ",
"[START]+[DOWN]  - Предыдущий маппинг джойстика             ",
"[START]+[LEFT]  - Быстрое сохранение                       ",
"[START]+[RIGHT] - Быстрая загрузка                         ",
"[START]+[A]     - Экранная клавиатура                      ",
"[START]+[B]     - Файловый менеджер                        ",
"                                                           ",
"[SELECT]+[UP]   - Увеличение громкости                     ",
"[SELECT]+[DOWN] - Уменьшение громкости                     ",
"[SELECT]+[LEFT] - [TFT режим] Уменьшение яркости           ",
"[SELECT]+[RIGHT]- [TFT режим] Увеличение яркости           ",
"[SELECT]+[A]    - [TFT режим] Блокировка клавиатуры        ",
"[SELECT]+[B]    - [TFT режим] Разблокировка клавиатуры     ",
"                                                           ",
"---------------------=[Джойстик в игре]=-------------------",
"[START]         - Вызов быстрого меню                      ",
"                 / Выход из файлового менеджера            ",
"[A]             - Действие назначенное в игре              ",
"[B]             - Действие назначенное в игре              ",
"[С]             - Действие назначенное в игре              ",
"                                                           ",
"------------=[Навигация в файловом менеджере]=-------------",
"[Курсорные клавиши:]                                       ",
"[Стрелка влево]  - Начало списка                           ",
"[Стрелка вправо] - Конец списка                            ",
"[Стрелка вверх]  - Предыдущий файл                         ",
"[Стрелка вниз]   - Следующий файл                          ",
"[PageUp]         - Страница вверх                          ",
"[PageDn]         - Страница вниз                           ",
"[Enter]          - Запуск образа                           ",
"[BackSpace]    - Выход на один каталог выше текущего уровня",
"[PrnScreen]   - Переключение просмотра заставки/содержимого",
"                                                           ",
"[Ins]/[Space]  - Пометка файлов для удаления               ",
"[Shift+Delete] - Вызов диалога удаления файлов             ",
"                                                           ",
"------------------=[Наcтройки эмулятора]=------------------",
"[F12]  - Настройки эмулятора (Доступны из файл менеджера)  ",
"                                                           ",
" [Boot go to]    - Выбор типа стартового экрана            ",
"  [LOGO]         - Показать заставку после старта          ",
"  [FILE MANAGER] - Показать Файловый менеджер после старта ",
"  [EMULATION]    - Запустить эмуляцию после старта         ",
"                                                           ",
" [Head Up Display]- Включение иконок поверх экрана         ",
"  [On]           - Включить отображение занятых дисководов,",
"                   процесса загрузки и слотов сохранения   ",
"  [Off]          - Чистый экран эмуляции                   ",
"                                                           ",
" [Tap load]      - Настройки загрузки .tap файлов          ",
"  [NORMAL LOADING] - Ручная загрузка образов .tap          ",
"                     (смотри раздел \"Работа с \"лентой\")    ",
"  [AUTOSTOP LOADING] - Автоматическая загрузка через ROM   ",
"  [FAST LOADING] - Быстрая загрузка через ROM              ",
"                                                           ",
" [Ext tape load pin] - Настройка номера пина               ",
"                       для внешней загрузки с магнитофона  ",
"  [GPIO22]           - Загрузка программ через GPIO22      ",
"  [GPIO29]           - Загрузка программ через GPIO29      ",
"                                                           ",
" [Def joy mode]  - Режим джойстика                         ",
"  [Ext>Kempston] - К [Kempston] подключен внешний джойстик ",
"  [Kbd>Kempston] - Эмуляция [Kempston] с клавиатуры        ",
"                   (Курсорные + RAlt)                      ",
"  [Kbd>Intface2] - Курсорные клавиши как Interface2        ",
"  [ Kbd>Cursor ] - Курсорные клавиши как CursorJoystick    ",
"  [-=+[NONE]+=-] - Все выключено                           ",
"                                                           ",
" [Reboot ZX before load] - Сброс эмуляции перед загрузкой  ",
"  [Yes] - Перезапускать эмуляцию при загрузке образов      ",
"  [No]  - Не перезапускать эмуляцию  при загрузке образов  ",
"                                                           ",
" [Snd mode] - Переключение вывода звука                    ",
"  [-=[Sound OFF]=-] - Выключить весь звук                  ",
"  [  Only Beeper  ] - Вывод звука только с бипера			",
"  [ Beeper+SoftAY ] - Звук с бипера и эмуляции AY-3-8910   ",
"  [ Beeper+SoftTS ] - Звук с бипера и эмуляции TurboSound  ",
"  [ HW TurboSound ] - Звук с аппаратного TurboSound        ",
"                                                           ",
" [Soft Sound Vol] - Громкость звука эмуляции               ",
"                   (работает только в Soft режиме)         ",
"                                                           ",
" [Video output] -Выбор типа подключения для вывода изображ.",
"  [   AUTO   ] - Автоопределение (VGA/HDMI)                ",
"  [   VGA    ] - Вывод на VGA разъем                       ",
"  [   HDMI   ] - Вывод на HDMI разъем                      ",
"  [  ST7789  ] - Вывод на ЖК экран с чипом ST7789          ",
"  [  ST7789V ] - Вывод на ЖК экран с чипом ST7789V         ",
"  [  ILI9341 ] - Вывод на ЖК экран с чипом ILI9341         ",
"  [ ILI9341V ] - Вывод на ЖК экран с чипом ILI9341V        ",
"  [  GC9A01  ] - Вывод на ЖК экран с чипом GC9A01          ",
"                   Для применения нужна перезагрузка.      ",
"                                                           ",
" [Video framerate] - Переключение частоты обновления       ",
"  [60Hz] - подходит для большинства LCD мониторов          ",
"  [72Hz] - подходит для большинства LCD/HDMI мониторов     ",
"  [75Hz] - подходит для LCD/HDMI/CRT мониторов             ",
"  [85Hz] - подходит для CRT мониторов                      ",
"                   Для применения нужна перезагрузка.      ",
"                                                           ",
" [LCD BrightLev] - Уровнь яркости подсветки ЖК экрана      ",
"               (работает только с режимами: ST7789,ST7789V,",
"                                   ILI9341,ILI9341V,GC9A01)",
"                                                           ",
" [LCD Rotate] - Поворот изображения ЖК экрана              ",
"  [Horizont R] - Горизонтальное, разъем дисплея справа     ",
"  [Vertical R] - Вертикальное, разъем дисплея снизу        ",
"  [Horizont L] - Горизонтальное, разъем дисплея слева      ",
"  [Vertical L] - Вертикальное, разъем дисплея сверху       ",
"               (работает только с режимами: ST7789,ST7789V,",
"                                   ILI9341,ILI9341V,GC9A01)",
"                   Для применения нужна перезагрузка.      ",
"                                                           ",
" [LCD inversion] - Инверсия изображения ЖК экрана          ",
"  [ NORMAL ] - Нормальное изображение                      ",
"  [INVERTED] - Инверсия цветов изображения                 ",
"               (работает только с режимами: ST7789,ST7789V,",
"                                   ILI9341,ILI9341V,GC9A01)",
"                   Для применения нужна перезагрузка.      ",
"                                                           ",
" [LCD Pixel format] - Формат пикселей ЖК экрана            ",
"  [ BGR ] - Blue Green Red, обратный порядок               ",
"  [ RGB ] - Red Green Blue, прямой порядок                 ",
"               (работает только с режимами: ST7789,ST7789V,",
"                                   ILI9341,ILI9341V,GC9A01)",
"                   Для применения нужна перезагрузка.      ",
"                                                           ",
" [HW TS Main Chip] - Выбор главного чипа TurboSound        ",
"  [Chip 1] - первый чип TurboSound адресует порт 0xFF      ",
"  [Chip 2] - первый чип TurboSound адресует порт 0xFE      ",
"                                                           ",
" [LOAD]     - Загрузить настройки c SD                     ",
" [DEFAULT]  - Загрузить настройки по умолчанию             ",
"              и перезаписать файл настроек                 ",
" [SAVE]     - Сохранить настройки на SD                    ",
" [UPDATE FIRMWARE]-Перезагрузка в режим обновления прошивки",
" [!!!REBOOT!!!]   - Перезагрузка контроллера               ",
"                                                           ",
},{
"                         Welcome!!!                        ",
"    This project is designed for minimalistic emulation    ",
"        computer ZX-Spectrum based on the controller       ",
 "                   [Raspberry Pi Pico]                    ",
"                                                           ",
" Project Group: https://t.me/ZX_MURMULATOR                 ",
"                                                           ",
"-----------------------==[Authors]==-----------------------",
" The author of the core and hardware:Alex Ekb (@Alex_Eburg)",
" TR-DOS support:               First Last(@First_0x26_Last)",
"                                      Cat's Tail(@tecnocat)",
" File Manager:                        Alex Ekb(@Alex_Eburg)",
"                                      Cat's Tail(@tecnocat)",
" SoftTurboSound Extension:            Alex Ekb(@Alex_Eburg)",
"                                      Cat's Tail(@tecnocat)",
"                                            Sa Gin(@sa gin)",
" TurboSound Extension:                Alex Ekb(@Alex_Eburg)",
"                                            Sa Gin(@sa gin)",
"                                      Cat's Tail(@tecnocat)",
" Soundrive Extension:                       Sa Gin(@sa gin)",
"                                      Cat's Tail(@tecnocat)",
" TFT driver:                          Alex Ekb(@Alex_Eburg)",
"                                      Cat's Tail(@tecnocat)",
"                                                           ",
"***********************************************************",
"                                                           ",
"-------------==[Emulator Keyboard Shortcuts]==-------------",
"[F1] - Help                                                ",
"[F2] - Quick Save Menu                                     ",
"[F3] - Quick Load Menu                                     ",
"[Win]/[Home] - File Manager                                ",
"                                                           ",
"[Ctrl+F1-F10] - Save the .z80 image to \"SAVE\" folder       ",
"[Shift+F1-F10] - .z80 Image load from \"SAVE\" folder        ",
"[Menu]/[Alt+F12]- Show free save slots at \"SAVE\" folder    ",
"[F11] - Enable disable HUD                                 ",
"[F12]/[PrnScreen] - Quick menu call                        ",
"[Pause] - Pauses emulation                                 ",
"                                                           ",
"[Ctrl+Alt+Del] - Reset the emulator                        ",
"[Ctrl+Alt+Ins] - NMI emulator                              ",
"[Shift+Alt+Del] - Reset the controller                     ",
"[Ctrl+Alt+BSpace]- Set default settings and                ",
"                                          reboot controller",
"[NumPad +]/[Alt+PgUp] - Volume Up of the emulation         ",
"[NumPad -]/[Alt+PgDn] - Volume Down of the emulation       ",
"[NumPad *]/[Alt+End] - Enable/disable Mute mode            ",
"[NumPad /]/[Alt+Del] -Switch the envelope in SoftTurboSound",
"                                                           ",
"---------------=[Working with \"Tape\" .tap]=--------------",
"[F5] - Start playing tape                                  ",
"[F6] - Stop the tape, repeat: rewind to the beginning      ",
"                                                           ",
"[F7] - Next block                                          ",
"[F8] - Previous block                                      ",
"[F9] - Eject current tape                                  ",
"                                                           ",
"*************************[Joystick]************************",
"[START]     - Quick menu call                              ",
"        / Exiting the file manager                         ",
"[A] - File Selection                                       ",
"[C] - Exit to top folder                                   ",
"                                                           ",
"---------------------=[Joystick Menu]=---------------------",
"[FILE BROWSER] - Calling the file manager                  ",
"  [KEYBOARD] - Calling the on-screen keyboard              ",
"  [SAVE] - List of slots to save games                     ",
"  [LOAD] - List of slots for load games                    ",
"  [TAPE] - Open the virtual tape management menu           ",
"  [POKE] - Cheat code entry menu                           ",
"  [HELP] - Help                                            ",
" 8bit Kempston[]-Enables translation of all joystick       ",
"                  button to the emulation.                 ",
"                  Exit the mode by START+SELECT            ",
"  [SETTINGS] - Emulation settings menu                     ",
"  Soft reset - Restarting the emulation                    ",
"  Hard reset - Restarting the system                       ",
"                                                           ",
"-------------------=[Joystick hat switch]=-----------------",
"[START]+[UP]    - Next joystick mapping                    ",
"[START]+[DOWN]  - Prev joystick mapping                    ",
"[START]+[LEFT]  - Quick save                               ",
"[START]+[RIGHT] - Quick load                               ",
"[START]+[A]     - On screen keyboard                       ",
"[START]+[B]     - File manager                             ",
"                                                           ",
"[SELECT]+[UP]   - Volume Up                                ",
"[SELECT]+[DOWN] - Volume Down                              ",
"[SELECT]+[LEFT] - [TFT mode] Brightness Level Down         ",
"[SELECT]+[RIGHT]- [TFT mode] Brightness Level Up           ",
"[SELECT]+[A]    - [TFT mode] Keyboard Lock                 ",
"[SELECT]+[B]    - [TFT mode] Keyboard Unlock               ",
"                                                           ",
"---------------------=[In-game joystick]=------------------",
"[START]       - Quick menu call                            ",
"         / Exiting the file manager                        ",
"[A] - The action assigned in the game                      ",
"[B] - The action assigned in the game                      ",
"[C] - The action assigned in the game                      ",
"                                                           ",
"----------------=[File Manager Navigation]=----------------",
"[Cursor keys:]                                             ",
"[Left arrow]  - Start of the list                          ",
"[Right arrow] - End of the list                            ",
"[Up Arrow]    - Previous file                              ",
"[Down arrow]  - Next file                                  ",
"[PageUp]      - Page up                                    ",
"[PageDn]      - Page down                                  ",
"[Enter]       - Launching the image                        ",
"[BackSpace]   - Exit one directory above the current level ",
"[PrnScreen]   - Switching the splash screen/content view   ",
"                                                           ",
"[Ins]/[Space] - Marking files for deletion                 ",
"[Shift+Delete]- Opens the file deletion dialog             ",
"                                                           ",
"-------------------=[Emulator Settings]=-------------------",
"[F12] - Emulator settings (Available from the file manager)",
"                                                           ",
" [Boot go to] - Select the type of start splash screen     ",
"  [LOGO]     - Show splash screen after the start          ",
"  [FILE MANAGER] - Show the File Manager after startup     ",
"  [EMULATION] - Start emulation after startup              ",
"                                                           ",
" [Head Up Display]- Enabling icons on top of the screen    ",
"  [On]            - Enable the display of occupied drives, ",
"                    loading process and save slots         ",
"  [Off]           - Clean emulation screen                 ",
"  [Time]          - HUD disappear by time                  ",
"                                                           ",
" [Tap load]  - .tap files loading settings                 ",
"  [NORMAL LOADING] - Manual loading of images .tap         ",
"                     (see \"Working with \"tape\" section)    ",
"  [AUTOSTOP LOADING] - Automatic loading via ROM           ",
"  [FAST LOADING] - Fast loading via ROM                    ",
"                                                           ",
" [Ext tape load pin] - Setting the pin number              ",
"                 for external loading from a tape recorder ",
"  [GPIO22] - Loading programs via GPIO22                   ",
"  [GPIO29] - Loading programs via GPIO29                   ",
"                                                           ",
" [Def joy mode] - Default joystick mode                    ",
"  [Ext>Kempston] - External joystick mapped to [Kempston]  ",
"  [Kbd>Kempston] - Emulation of [Kempston] from keyboard   ",
"                   (Cursors + RAlt)                        ",
"  [Kbd>Intface2] - Cursor keys as Interface2               ",
"  [ Kbd>Cursor ] - Cursor keys as CursorJoystick           ",
"  [-=+[NONE]+=-] - Everything is off                       ",
"                                                           ",
" [Reboot ZX before load] - Reset emulation before loading  ",
"  [Yes] - Restart emulation when loading images            ",
"  [No] - Do not restart emulation when loading images      ",
"                                                           ",
" [Snd mode] - Switching the audio output                   ",
"  [-=[Sound OFF]=-] - Turn off all sound                   ",
"  [ Only Beeper ] - Audio only from the beeper             ",
"  [ Beeper+SoftAY ] - Beeper and emulation AY-3-8910       ",
"  [ Beeper+SoftTS ] - Beeper and TurboSound emulation      ",
"  [ HW TurboSound ] - External hardware TurboSound         ",
"                                                           ",
" [Soft Sound Vol] - Sound Volume of the emulation          ",
"                    (works only in Software emulation mode)",
"                                                           ",
" [Video output] - Video output type                        ",
"  [ AUTO ] - Auto Detection (VGA/HDMI)                     ",
"  [ VGA ] - Output to the VGA connector                    ",
"  [ HDMI ] - Output to the HDMI connector                  ",
"  [ ST7789 ]  - Output to LCD screen with the ST7789 chip  ",
"  [ ST7789V ] - Output to LCD screen with the ST7789V chip ",
"  [ ILI9341 ] - Output to LCD screen with the ILI9341 chip ",
"  [ ILI9341V ]- Output to LCD screen with the ILI9341V chip",
"  [ GC9A01 ]  - Output to LCD screen with GC9A01 chip      ",
"           A reboot is required to apply mode.             ",
"                                                           ",
" [Video framerate] - Switching the vertical refresh rate   ",
"  [60Hz] - Suitable for most LCD monitors                  ",
"  [72Hz] - Suitable for most LCD/HDMI monitors             ",
"  [75Hz] - Suitable for LCD/HDMI/CRT monitors              ",
"  [85Hz] - Suitable for CRT monitors                       ",
"           A reboot is required to apply mode.             ",
"                                                           ",
" [LCD BrightLev] - The brightness level for LCD backlight  ",
"                   (works only with modes: ST7789,ST7789V, ",
"                                   ILI9341,ILI9341V,GC9A01)",
"                                                           ",
" [LCD Rotate] - Rotate the image of the LCD screen         ",
"  [Horizont R] - Horizontal, display connector on the right",
"  [Vertical R] - Vertical, display connector from below    ",
"  [Horizont L] - Horizontal, display connector on the left ",
"  [Vertical L] - Vertical, display connector from above    ",
"                    (works only with modes: ST7789,ST7789V,",
"                                   ILI9341,ILI9341V,GC9A01)",
"           A reboot is required to apply mode.             ",
"                                                           ",
" [LCD inversion] - Inversion of the LCD screen image       ",
" [ NORMAL ] - Normal image                                 ",
" [INVERTED] - Inversion of image colors                    ",
"                    (works only with modes: ST7789,ST7789V,",
"                                   ILI9341,ILI9341V,GC9A01)",
"           A reboot is required to apply mode.             ",
"                                                           ",
" [LCD Pixel format] - LCD screen pixel format              ",
" [ BGR ] - Blue Green Red, reverse order                   ",
" [ RGB ] - Red Green Blue, forward order                   ",
"                    (works only with modes: ST7789,ST7789V,",
"                                   ILI9341,ILI9341V,GC9A01)",
"           A reboot is required to apply mode.             ",
"                                                           ",
" [HW TS Main Chip] - TurboSound main chip selection        ",
" [Chip 1] - the first TurboSound chip addresses port 0xFF  ",
" [Chip 2] - the first TurboSound chip addresses port 0xFE  ",
"                                                           ",
" [LOAD]     - Reload settings from SD                      ",
" [DEFAULT]  - Load default settings                        ",
"                           and overwrite the settings file ",
" [SAVE]     - Save settings to SD card                     ",
" [UPDATE FIRMWARE] - Reboot to firmware update mode        ",
" [!!!REBOOT!!!] - Restart the controller                   "
}
};

/*
"-----------------=[Команды NMI Отладчика]=-----------------",
" 1 - Система счисления 16/10;                              ",
" 2 - Дамп/символьное представление;                        ",
" 3 - внесение числа в текущ. регистр;                      ",
" 4 - внесение в текущую сетку памяти;                      ",
" CS+5 - на 64 адреса назад;                                ",
" CS+6 - на 1 адрес назад;                                  ",
" CS+7 - на 1 адрес вперед;                                 ",
" CS+8 - на 64 адреса вперед;                               ",
" CS+9 - перейти к предыд. регистру;                        ",
" CS+0 - перейти к следующ. регистру;                       ",
" SS+7 - вызов подпрогр. по адресу;                         ",
" SS+0 - выход из монитора в Basic;                         ",
" ПРОБЕЛ - выделение ячейки по номеру.                      "
*/